blog: v1.14.5 release announcement
fluent/fluentd-website pull request #174
Opened 2022-02-08 07:14 UTC by daipom

Add a draft of v1.14.5 release announcement.

2022-02-08 07:28 UTC, kenhys commented on content/blog/draft_fluentd-v1.14.5-has-been-released.md
> +### `in_http`: Add support for "Application/x-ndjson"
```suggestion
### `in_http`: Add support for "application/x-ndjson"
```

2022-02-08 07:28 UTC, kenhys commented on content/blog/draft_fluentd-v1.14.5-has-been-released.md
> +In this release, `in_http` supports the new Content-Type "Application/x-ndjson".
```suggestion
In this release, `in_http` supports the new Content-Type "application/x-ndjson".
```

2022-02-08 07:29 UTC, fujimotos approved these changes
全体的に良い感じだと思いました！細かいコメントをいくつかつけましたので参照下さい。

2022-02-08 07:29 UTC, fujimotos commented on content/blog/draft_fluentd-v1.14.5-has-been-released.md
> +With this release, `connect_timeout` is now reliably applied to TLS tranport
transport

2022-02-08 07:29 UTC, fujimotos commented on content/blog/draft_fluentd-v1.14.5-has-been-released.md
> +* Fix "invalid byte sequence is replaced" warning not to log out invalid characters. [#3596](https://github.com/fluent/fluentd/pull/3596)
「ログを吐き出す」の趣旨なら`log out`ではなく`write out`かなんかだと思います。
（"log out"だと文字通り「ログアウト」の意味になるため）

2022-02-08 07:33 UTC, daipom commented on content/blog/draft_fluentd-v1.14.5-has-been-released.md
> +### `in_http`: Add support for "Application/x-ndjson"
ありがとうございます。
小文字が正しいんですね。
それなら https://github.com/fluent/fluentd/pull/3623 の方も直した方がよさそうですか？

2022-02-08 07:36 UTC, daipom commented on content/blog/draft_fluentd-v1.14.5-has-been-released.md
> +With this release, `connect_timeout` is now reliably applied to TLS tranport
すみません、どういうことでしょうか？

2022-02-08 07:38 UTC, daipom commented on content/blog/draft_fluentd-v1.14.5-has-been-released.md
> +* Fix "invalid byte sequence is replaced" warning not to log out invalid characters. [#3596](https://github.com/fluent/fluentd/pull/3596)
ありがとうございます！`log out`はおかしいですね、`write out`にします！

2022-02-08 07:40 UTC, fujimotos commented on content/blog/draft_fluentd-v1.14.5-has-been-released.md
> +With this release, `connect_timeout` is now reliably applied to TLS tranport
`tranport -> transport`という趣旨でした！

2022-02-08 07:41 UTC, daipom commented on content/blog/draft_fluentd-v1.14.5-has-been-released.md
> +With this release, `connect_timeout` is now reliably applied to TLS tranport
わわわ、40行目の方ですね、、すみません、ありがとうございます。

2022-02-08 07:43 UTC, fujimotos commented on content/blog/draft_fluentd-v1.14.5-has-been-released.md
> +### `in_http`: Add support for "Application/x-ndjson"
CHANGELOGは直しました！

2022-02-08 07:49 UTC, daipom commented
ご指摘ありがとうございます。
それぞれ修正しました。

2022-02-08 08:58 UTC, ashie requested changes

2022-02-08 08:58 UTC, ashie commented on content/blog/draft_fluentd-v1.14.5-has-been-released.md
> +RubyInstaller 3.1 has switched from C-Runtime to UCRT, and the ruby and gem
`from` isn't needed, or `RubyInstaller 3.1 has switched C-Runtime from MSVCRT to UCRT`.

2022-02-08 08:58 UTC, ashie commented on content/blog/draft_fluentd-v1.14.5-has-been-released.md
> +could not be installed in the environment.
事実誤認がありそうです。
「Fluentdの依存gemが`x64-mingw-ucrt`版をリリースしていなかったから」ではなく、「Fluentdの`x64-mingw-ucrt`がリリースされていなかったから」Windowsの場合にのみ必要なgemがインストールできていませんでした。

x64-mingw-ucrtではx86-mingw32でもx64-mingw32でもないgenericなプラットフォーム用のfluentd gemがインストールされていたため、以下の部分が抜けるということです。
https://github.com/fluent/fluentd/blob/98b236e0396564bfad84e318fb6fb5308dbbdce4/fluentd.gemspec#L36-L43

今回x64-mingw-ucrt用のFluentd gemをリリースするようにしたことで、上記部分が正しく反映されるようになりました。

2022-02-08 09:35 UTC, daipom commented on content/blog/draft_fluentd-v1.14.5-has-been-released.md
> +RubyInstaller 3.1 has switched from C-Runtime to UCRT, and the ruby and gem
ありがとうございます。完全に誤っていました。直しました。

2022-02-08 09:36 UTC, daipom commented on content/blog/draft_fluentd-v1.14.5-has-been-released.md
> +could not be installed in the environment.
ありがとうございます。誤認していました。直しました。

2022-02-08 09:37 UTC, fujimotos commented
オッケーそうですね！これで明日、リリースの時に私の方でマージします。

2022-02-08 09:40 UTC, ashie approved these changes

2022-02-09 02:28 UTC, daipom commented
すみません、今気がついたのですが、以下の修正を今行ってもよいでしょうか？
`the`と`that`を間違えて打っていた用に思います。

```diff
### `out_forward`: Fix hang-up issue during TLS handshake

- There was a known issue the TLS handshake takes a long time or hangs when
+ There was a known issue that TLS handshake takes a long time or hangs when
```

2022-02-09 03:12 UTC, merged

2022-02-09 03:21 UTC, fujimotos commented
@daipom 618a9763 で修正してプッシュしました。無事公開済みです：

https://www.fluentd.org/blog/fluentd-v1.14.5-has-been-released

2022-02-09 05:20 UTC, daipom commented
皆様ありがとうございます！！