Follow updated CHANGELOG.md heading styles
fluent/fluentd-website pull request #178
Opened 2022-02-28 10:08 UTC by kenhys

Recently, it was found that the heading style in CHANGELOG.md was unexpectedly changed.
It has been fixed with https://github.com/fluent/fluentd/pull/3648.
Then blog entries that contain links to CHANGELOG.md should be also updated.

2022-02-28 12:09 UTC, ashie requested changes

2022-02-28 12:09 UTC, ashie commented on content/blog/20210929_fluentd-v1.14.1-has-been-released.md
> +We have released v1.14.1. ChangeLog is [here](https://github.com/fluent/fluentd/blob/master/CHANGELOG.md#release-v1141---20210829).
```suggestion
We have released v1.14.1. ChangeLog is [here](https://github.com/fluent/fluentd/blob/master/CHANGELOG.md#release-v1141---20210929).
```

2022-02-28 12:11 UTC, ashie approved these changes

2022-02-28 12:12 UTC, merged

2022-03-01 00:55 UTC, kenhys commented
Thanks, I've missed it. @ashie