add responsive table
fluent/fluentd-website pull request #218
Opened 2022-05-20 16:43 UTC by Arhell

resolve https://github.com/fluent/fluentd-website/issues/217

2022-05-21 08:47 UTC, Arhell commented
cc @ashie

2022-05-26 05:12 UTC, ashie approved these changes

2022-05-26 05:12 UTC, ashie commented on assets/css/responsive.css
> +	/* Small devices (tablets, 768px and less) */
Could you revert the indent of this comment?

2022-05-26 05:13 UTC, ashie requested changes
Waiting to fix indent.

2022-05-26 07:40 UTC, merged